source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Minutas' do
	pod 'FSCalendar'
	pod 'Fabric'
	pod 'TwitterKit'
	pod 'Bolts'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'DatePickerCell'
end